include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - valid_regexps
    - always_declare_return_types
    - prefer_single_quotes
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_this
    - use_key_in_widget_constructors

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
